'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4216
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CLC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property CLC64x64() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CLC64x64", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property CLC96x96() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CLC96x96", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property CLCAlerta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCAlerta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCAlertaG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCAlertaG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCAlertaG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCAlertaG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCApelo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCApelo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCFundo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCFundo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCIconePrep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCIconePrep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCInicio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCInicio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CLCVersao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLCVersao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Licença concedida à Intermesa Trading Ltda..
        '''</summary>
        Public ReadOnly Property INFO_LICENCA() As String
            Get
                Return ResourceManager.GetString("INFO_LICENCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Objetivos do Sistema:
        '''
        '''Colaborar com a venda oferencendo oportunidades de:
        '''
        '''1) controle de pedido,
        '''2) emissão de documentos para solicitação de fornecimento,
        '''3) particionamento deste pedido primário em inúmeras ordens de venda,
        '''4) o apoio à logística de distribuição e, 
        '''
        '''        finalmente,
        '''
        '''5) acompanhamento de obrigações financeiras..
        '''</summary>
        Public ReadOnly Property INFO_OBJETIVOS() As String
            Get
                Return ResourceManager.GetString("INFO_OBJETIVOS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
