'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace www
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.intermesa.com.br/interface/", ConfigurationName:="www.ConsultaSoap")>  _
    Public Interface ConsultaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ObtemOpcArmazem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaObs", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaAvaria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/TrocaUnidMedida", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As Integer, ByVal Unid As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaPesoBalanca", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As Double, ByVal Bruto As Double, ByVal QtdPecas As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/AtualizaStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaLocaliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As Integer, ByVal Coluna As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/CarregaCombosUsu", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqApres", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqRefCli", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqCodBarras", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet
        
        'CODEGEN: Parameter 'ArquivoBinResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ArquivoBin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoBin(ByVal request As www.ArquivoBinRequest) As www.ArquivoBinResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/DSCarregaRem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/DSGravaRem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ArquivoMomentoModif", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoMomentoModif(ByVal Arquivo As String) As Date
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ArquivoBin", WrapperNamespace:="http://www.intermesa.com.br/interface/", IsWrapped:=true)>  _
    Partial Public Class ArquivoBinRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0)>  _
        Public ArquivoEmDown As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoEmDown As String)
            MyBase.New
            Me.ArquivoEmDown = ArquivoEmDown
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ArquivoBinResponse", WrapperNamespace:="http://www.intermesa.com.br/interface/", IsWrapped:=true)>  _
    Partial Public Class ArquivoBinResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public ArquivoBinResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoBinResult() As Byte)
            MyBase.New
            Me.ArquivoBinResult = ArquivoBinResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ConsultaSoapChannel
        Inherits www.ConsultaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConsultaSoapClient
        Inherits System.ServiceModel.ClientBase(Of www.ConsultaSoap)
        Implements www.ConsultaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet Implements www.ConsultaSoap.ObtemOpcArmazem
            Return MyBase.Channel.ObtemOpcArmazem(Armazem)
        End Function
        
        Public Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet Implements www.ConsultaSoap.SalvaObs
            Return MyBase.Channel.SalvaObs(Usuario, Senha, Equip, Etiqueta, Texto)
        End Function
        
        Public Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet Implements www.ConsultaSoap.SalvaAvaria
            Return MyBase.Channel.SalvaAvaria(Usuario, Senha, Equip, Etiqueta, Texto)
        End Function
        
        Public Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As Integer, ByVal Unid As String) As System.Data.DataSet Implements www.ConsultaSoap.TrocaUnidMedida
            Return MyBase.Channel.TrocaUnidMedida(Usuario, Senha, Equip, Pedido, Item, Unid)
        End Function
        
        Public Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As Double, ByVal Bruto As Double, ByVal QtdPecas As Integer) As System.Data.DataSet Implements www.ConsultaSoap.SalvaPesoBalanca
            Return MyBase.Channel.SalvaPesoBalanca(Usuario, Senha, Equip, Etiqueta, Liquido, Bruto, QtdPecas)
        End Function
        
        Public Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet Implements www.ConsultaSoap.AtualizaStatus
            Return MyBase.Channel.AtualizaStatus(Usuario, Senha, Equip, Etiqueta, Status)
        End Function
        
        Public Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As Integer, ByVal Coluna As Integer) As System.Data.DataSet Implements www.ConsultaSoap.SalvaLocaliza
            Return MyBase.Channel.SalvaLocaliza(Usuario, Senha, Equip, Etiqueta, Armazem, Num, Praca, Linha, Coluna)
        End Function
        
        Public Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet Implements www.ConsultaSoap.CarregaCombosUsu
            Return MyBase.Channel.CarregaCombosUsu(Usuario)
        End Function
        
        Public Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet Implements www.ConsultaSoap.RastrEtiqApres
            Return MyBase.Channel.RastrEtiqApres(EtiqApres)
        End Function
        
        Public Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet Implements www.ConsultaSoap.RastrEtiqRefCli
            Return MyBase.Channel.RastrEtiqRefCli(RefCli)
        End Function
        
        Public Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet Implements www.ConsultaSoap.RastrEtiqCodBarras
            Return MyBase.Channel.RastrEtiqCodBarras(AplRefBarras)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaSoap_ArquivoBin(ByVal request As www.ArquivoBinRequest) As www.ArquivoBinResponse Implements www.ConsultaSoap.ArquivoBin
            Return MyBase.Channel.ArquivoBin(request)
        End Function
        
        Public Function ArquivoBin(ByVal ArquivoEmDown As String) As Byte()
            Dim inValue As www.ArquivoBinRequest = New www.ArquivoBinRequest
            inValue.ArquivoEmDown = ArquivoEmDown
            Dim retVal As www.ArquivoBinResponse = CType(Me,www.ConsultaSoap).ArquivoBin(inValue)
            Return retVal.ArquivoBinResult
        End Function
        
        Public Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet Implements www.ConsultaSoap.DSCarregaRem
            Return MyBase.Channel.DSCarregaRem(Usuario, Senha, Equip, Consulta)
        End Function
        
        Public Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet Implements www.ConsultaSoap.DSGravaRem
            Return MyBase.Channel.DSGravaRem(Usuario, Senha, Equip, Consulta)
        End Function
        
        Public Function ArquivoMomentoModif(ByVal Arquivo As String) As Date Implements www.ConsultaSoap.ArquivoMomentoModif
            Return MyBase.Channel.ArquivoMomentoModif(Arquivo)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.intermesa.com.br/interface/", ConfigurationName:="www.ConsultaHttpGet")>  _
    Public Interface ConsultaHttpGet
        
        'CODEGEN: Generating message contract since the operation ObtemOpcArmazem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ObtemOpcArmazemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ObtemOpcArmazemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtemOpcArmazem(ByVal request As www.ObtemOpcArmazemRequest) As www.ObtemOpcArmazemResponse
        
        'CODEGEN: Generating message contract since the operation SalvaObs is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaObsRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaObsResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaObs(ByVal request As www.SalvaObsRequest) As www.SalvaObsResponse
        
        'CODEGEN: Generating message contract since the operation SalvaAvaria is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaAvariaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaAvariaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaAvaria(ByVal request As www.SalvaAvariaRequest) As www.SalvaAvariaResponse
        
        'CODEGEN: Generating message contract since the operation TrocaUnidMedida is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/TrocaUnidMedidaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/TrocaUnidMedidaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function TrocaUnidMedida(ByVal request As www.TrocaUnidMedidaRequest) As www.TrocaUnidMedidaResponse
        
        'CODEGEN: Generating message contract since the operation SalvaPesoBalanca is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaPesoBalancaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaPesoBalancaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaPesoBalanca(ByVal request As www.SalvaPesoBalancaRequest) As www.SalvaPesoBalancaResponse
        
        'CODEGEN: Generating message contract since the operation AtualizaStatus is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/AtualizaStatusRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/AtualizaStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AtualizaStatus(ByVal request As www.AtualizaStatusRequest) As www.AtualizaStatusResponse
        
        'CODEGEN: Generating message contract since the operation SalvaLocaliza is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaLocalizaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaLocalizaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaLocaliza(ByVal request As www.SalvaLocalizaRequest) As www.SalvaLocalizaResponse
        
        'CODEGEN: Generating message contract since the operation CarregaCombosUsu is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/CarregaCombosUsuRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/CarregaCombosUsuResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function CarregaCombosUsu(ByVal request As www.CarregaCombosUsuRequest) As www.CarregaCombosUsuResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqApres is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqApresRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqApresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqApres(ByVal request As www.RastrEtiqApresRequest) As www.RastrEtiqApresResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqRefCli is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqRefCliRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqRefCliResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqRefCli(ByVal request As www.RastrEtiqRefCliRequest) As www.RastrEtiqRefCliResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqCodBarras is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqCodBarrasRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqCodBarrasResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqCodBarras(ByVal request As www.RastrEtiqCodBarrasRequest) As www.RastrEtiqCodBarrasResponse
        
        'CODEGEN: Generating message contract since the operation ArquivoBin is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoBinRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoBinResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoBin(ByVal request As www.ArquivoBinRequest1) As www.ArquivoBinResponse1
        
        'CODEGEN: Generating message contract since the operation DSCarregaRem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSCarregaRemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSCarregaRemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSCarregaRem(ByVal request As www.DSCarregaRemRequest) As www.DSCarregaRemResponse
        
        'CODEGEN: Generating message contract since the operation DSGravaRem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSGravaRemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSGravaRemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSGravaRem(ByVal request As www.DSGravaRemRequest) As www.DSGravaRemResponse
        
        'CODEGEN: Generating message contract since the operation ArquivoMomentoModif is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoMomentoModifRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoMomentoModifResponse"& _ 
            ""),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoMomentoModif(ByVal request As www.ArquivoMomentoModifRequest) As www.ArquivoMomentoModifResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtemOpcArmazemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Armazem As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Armazem As String)
            MyBase.New
            Me.Armazem = Armazem
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtemOpcArmazemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaObsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Texto As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Texto = Texto
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaObsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaAvariaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Texto As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Texto = Texto
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaAvariaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TrocaUnidMedidaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Pedido As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Item As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Unid As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As String, ByVal Unid As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Pedido = Pedido
            Me.Item = Item
            Me.Unid = Unid
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TrocaUnidMedidaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaPesoBalancaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Liquido As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Bruto As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public QtdPecas As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As String, ByVal Bruto As String, ByVal QtdPecas As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Liquido = Liquido
            Me.Bruto = Bruto
            Me.QtdPecas = QtdPecas
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaPesoBalancaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Status As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Status = Status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaLocalizaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Armazem As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Num As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public Praca As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public Linha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Coluna As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As String, ByVal Coluna As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Armazem = Armazem
            Me.Num = Num
            Me.Praca = Praca
            Me.Linha = Linha
            Me.Coluna = Coluna
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaLocalizaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CarregaCombosUsuRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String)
            MyBase.New
            Me.Usuario = Usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CarregaCombosUsuResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqApresRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public EtiqApres As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EtiqApres As String)
            MyBase.New
            Me.EtiqApres = EtiqApres
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqApresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqRefCliRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RefCli As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RefCli As String)
            MyBase.New
            Me.RefCli = RefCli
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqRefCliResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqCodBarrasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AplRefBarras As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AplRefBarras As String)
            MyBase.New
            Me.AplRefBarras = AplRefBarras
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqCodBarrasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoBinRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public ArquivoEmDown As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoEmDown As String)
            MyBase.New
            Me.ArquivoEmDown = ArquivoEmDown
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoBinResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public base64Binary() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal base64Binary() As Byte)
            MyBase.New
            Me.base64Binary = base64Binary
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSCarregaRemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Consulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Consulta = Consulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSCarregaRemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSGravaRemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Consulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Consulta = Consulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSGravaRemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoMomentoModifRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Arquivo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Arquivo As String)
            MyBase.New
            Me.Arquivo = Arquivo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoMomentoModifResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0)>  _
        Public dateTime As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dateTime As Date)
            MyBase.New
            Me.dateTime = dateTime
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ConsultaHttpGetChannel
        Inherits www.ConsultaHttpGet, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConsultaHttpGetClient
        Inherits System.ServiceModel.ClientBase(Of www.ConsultaHttpGet)
        Implements www.ConsultaHttpGet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_ObtemOpcArmazem(ByVal request As www.ObtemOpcArmazemRequest) As www.ObtemOpcArmazemResponse Implements www.ConsultaHttpGet.ObtemOpcArmazem
            Return MyBase.Channel.ObtemOpcArmazem(request)
        End Function
        
        Public Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet
            Dim inValue As www.ObtemOpcArmazemRequest = New www.ObtemOpcArmazemRequest
            inValue.Armazem = Armazem
            Dim retVal As www.ObtemOpcArmazemResponse = CType(Me,www.ConsultaHttpGet).ObtemOpcArmazem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_SalvaObs(ByVal request As www.SalvaObsRequest) As www.SalvaObsResponse Implements www.ConsultaHttpGet.SalvaObs
            Return MyBase.Channel.SalvaObs(request)
        End Function
        
        Public Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
            Dim inValue As www.SalvaObsRequest = New www.SalvaObsRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Texto = Texto
            Dim retVal As www.SalvaObsResponse = CType(Me,www.ConsultaHttpGet).SalvaObs(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_SalvaAvaria(ByVal request As www.SalvaAvariaRequest) As www.SalvaAvariaResponse Implements www.ConsultaHttpGet.SalvaAvaria
            Return MyBase.Channel.SalvaAvaria(request)
        End Function
        
        Public Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
            Dim inValue As www.SalvaAvariaRequest = New www.SalvaAvariaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Texto = Texto
            Dim retVal As www.SalvaAvariaResponse = CType(Me,www.ConsultaHttpGet).SalvaAvaria(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_TrocaUnidMedida(ByVal request As www.TrocaUnidMedidaRequest) As www.TrocaUnidMedidaResponse Implements www.ConsultaHttpGet.TrocaUnidMedida
            Return MyBase.Channel.TrocaUnidMedida(request)
        End Function
        
        Public Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As String, ByVal Unid As String) As System.Data.DataSet
            Dim inValue As www.TrocaUnidMedidaRequest = New www.TrocaUnidMedidaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Pedido = Pedido
            inValue.Item = Item
            inValue.Unid = Unid
            Dim retVal As www.TrocaUnidMedidaResponse = CType(Me,www.ConsultaHttpGet).TrocaUnidMedida(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_SalvaPesoBalanca(ByVal request As www.SalvaPesoBalancaRequest) As www.SalvaPesoBalancaResponse Implements www.ConsultaHttpGet.SalvaPesoBalanca
            Return MyBase.Channel.SalvaPesoBalanca(request)
        End Function
        
        Public Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As String, ByVal Bruto As String, ByVal QtdPecas As String) As System.Data.DataSet
            Dim inValue As www.SalvaPesoBalancaRequest = New www.SalvaPesoBalancaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Liquido = Liquido
            inValue.Bruto = Bruto
            inValue.QtdPecas = QtdPecas
            Dim retVal As www.SalvaPesoBalancaResponse = CType(Me,www.ConsultaHttpGet).SalvaPesoBalanca(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_AtualizaStatus(ByVal request As www.AtualizaStatusRequest) As www.AtualizaStatusResponse Implements www.ConsultaHttpGet.AtualizaStatus
            Return MyBase.Channel.AtualizaStatus(request)
        End Function
        
        Public Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet
            Dim inValue As www.AtualizaStatusRequest = New www.AtualizaStatusRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Status = Status
            Dim retVal As www.AtualizaStatusResponse = CType(Me,www.ConsultaHttpGet).AtualizaStatus(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_SalvaLocaliza(ByVal request As www.SalvaLocalizaRequest) As www.SalvaLocalizaResponse Implements www.ConsultaHttpGet.SalvaLocaliza
            Return MyBase.Channel.SalvaLocaliza(request)
        End Function
        
        Public Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As String, ByVal Coluna As String) As System.Data.DataSet
            Dim inValue As www.SalvaLocalizaRequest = New www.SalvaLocalizaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Armazem = Armazem
            inValue.Num = Num
            inValue.Praca = Praca
            inValue.Linha = Linha
            inValue.Coluna = Coluna
            Dim retVal As www.SalvaLocalizaResponse = CType(Me,www.ConsultaHttpGet).SalvaLocaliza(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_CarregaCombosUsu(ByVal request As www.CarregaCombosUsuRequest) As www.CarregaCombosUsuResponse Implements www.ConsultaHttpGet.CarregaCombosUsu
            Return MyBase.Channel.CarregaCombosUsu(request)
        End Function
        
        Public Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet
            Dim inValue As www.CarregaCombosUsuRequest = New www.CarregaCombosUsuRequest
            inValue.Usuario = Usuario
            Dim retVal As www.CarregaCombosUsuResponse = CType(Me,www.ConsultaHttpGet).CarregaCombosUsu(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_RastrEtiqApres(ByVal request As www.RastrEtiqApresRequest) As www.RastrEtiqApresResponse Implements www.ConsultaHttpGet.RastrEtiqApres
            Return MyBase.Channel.RastrEtiqApres(request)
        End Function
        
        Public Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet
            Dim inValue As www.RastrEtiqApresRequest = New www.RastrEtiqApresRequest
            inValue.EtiqApres = EtiqApres
            Dim retVal As www.RastrEtiqApresResponse = CType(Me,www.ConsultaHttpGet).RastrEtiqApres(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_RastrEtiqRefCli(ByVal request As www.RastrEtiqRefCliRequest) As www.RastrEtiqRefCliResponse Implements www.ConsultaHttpGet.RastrEtiqRefCli
            Return MyBase.Channel.RastrEtiqRefCli(request)
        End Function
        
        Public Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet
            Dim inValue As www.RastrEtiqRefCliRequest = New www.RastrEtiqRefCliRequest
            inValue.RefCli = RefCli
            Dim retVal As www.RastrEtiqRefCliResponse = CType(Me,www.ConsultaHttpGet).RastrEtiqRefCli(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_RastrEtiqCodBarras(ByVal request As www.RastrEtiqCodBarrasRequest) As www.RastrEtiqCodBarrasResponse Implements www.ConsultaHttpGet.RastrEtiqCodBarras
            Return MyBase.Channel.RastrEtiqCodBarras(request)
        End Function
        
        Public Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet
            Dim inValue As www.RastrEtiqCodBarrasRequest = New www.RastrEtiqCodBarrasRequest
            inValue.AplRefBarras = AplRefBarras
            Dim retVal As www.RastrEtiqCodBarrasResponse = CType(Me,www.ConsultaHttpGet).RastrEtiqCodBarras(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_ArquivoBin(ByVal request As www.ArquivoBinRequest1) As www.ArquivoBinResponse1 Implements www.ConsultaHttpGet.ArquivoBin
            Return MyBase.Channel.ArquivoBin(request)
        End Function
        
        Public Function ArquivoBin(ByVal ArquivoEmDown As String) As Byte()
            Dim inValue As www.ArquivoBinRequest1 = New www.ArquivoBinRequest1
            inValue.ArquivoEmDown = ArquivoEmDown
            Dim retVal As www.ArquivoBinResponse1 = CType(Me,www.ConsultaHttpGet).ArquivoBin(inValue)
            Return retVal.base64Binary
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_DSCarregaRem(ByVal request As www.DSCarregaRemRequest) As www.DSCarregaRemResponse Implements www.ConsultaHttpGet.DSCarregaRem
            Return MyBase.Channel.DSCarregaRem(request)
        End Function
        
        Public Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
            Dim inValue As www.DSCarregaRemRequest = New www.DSCarregaRemRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Consulta = Consulta
            Dim retVal As www.DSCarregaRemResponse = CType(Me,www.ConsultaHttpGet).DSCarregaRem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_DSGravaRem(ByVal request As www.DSGravaRemRequest) As www.DSGravaRemResponse Implements www.ConsultaHttpGet.DSGravaRem
            Return MyBase.Channel.DSGravaRem(request)
        End Function
        
        Public Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
            Dim inValue As www.DSGravaRemRequest = New www.DSGravaRemRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Consulta = Consulta
            Dim retVal As www.DSGravaRemResponse = CType(Me,www.ConsultaHttpGet).DSGravaRem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function www_ConsultaHttpGet_ArquivoMomentoModif(ByVal request As www.ArquivoMomentoModifRequest) As www.ArquivoMomentoModifResponse Implements www.ConsultaHttpGet.ArquivoMomentoModif
            Return MyBase.Channel.ArquivoMomentoModif(request)
        End Function
        
        Public Function ArquivoMomentoModif(ByVal Arquivo As String) As Date
            Dim inValue As www.ArquivoMomentoModifRequest = New www.ArquivoMomentoModifRequest
            inValue.Arquivo = Arquivo
            Dim retVal As www.ArquivoMomentoModifResponse = CType(Me,www.ConsultaHttpGet).ArquivoMomentoModif(inValue)
            Return retVal.dateTime
        End Function
    End Class
End Namespace
