'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace wwwisc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.intermesa.com.br/interface/", ConfigurationName:="wwwisc.ConsultaSoap")>  _
    Public Interface ConsultaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ObtemOpcArmazem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaObs", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaAvaria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/TrocaUnidMedida", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As Integer, ByVal Unid As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaPesoBalanca", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As Double, ByVal Bruto As Double, ByVal QtdPecas As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/AtualizaStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/SalvaLocaliza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As Integer, ByVal Coluna As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/CarregaCombosUsu", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqApres", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqRefCli", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/RastrEtiqCodBarras", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet
        
        'CODEGEN: Parameter 'ArquivoBinResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ArquivoBin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoBin(ByVal request As wwwisc.ArquivoBinRequest) As wwwisc.ArquivoBinResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/DSCarregaRem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/DSGravaRem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ArquivoMomentoModif", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoMomentoModif(ByVal Arquivo As String) As Date
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ArquivoBin", WrapperNamespace:="http://www.intermesa.com.br/interface/", IsWrapped:=true)>  _
    Partial Public Class ArquivoBinRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0)>  _
        Public ArquivoEmDown As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoEmDown As String)
            MyBase.New
            Me.ArquivoEmDown = ArquivoEmDown
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ArquivoBinResponse", WrapperNamespace:="http://www.intermesa.com.br/interface/", IsWrapped:=true)>  _
    Partial Public Class ArquivoBinResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public ArquivoBinResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoBinResult() As Byte)
            MyBase.New
            Me.ArquivoBinResult = ArquivoBinResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ConsultaSoapChannel
        Inherits wwwisc.ConsultaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConsultaSoapClient
        Inherits System.ServiceModel.ClientBase(Of wwwisc.ConsultaSoap)
        Implements wwwisc.ConsultaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.ObtemOpcArmazem
            Return MyBase.Channel.ObtemOpcArmazem(Armazem)
        End Function
        
        Public Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.SalvaObs
            Return MyBase.Channel.SalvaObs(Usuario, Senha, Equip, Etiqueta, Texto)
        End Function
        
        Public Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.SalvaAvaria
            Return MyBase.Channel.SalvaAvaria(Usuario, Senha, Equip, Etiqueta, Texto)
        End Function
        
        Public Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As Integer, ByVal Unid As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.TrocaUnidMedida
            Return MyBase.Channel.TrocaUnidMedida(Usuario, Senha, Equip, Pedido, Item, Unid)
        End Function
        
        Public Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As Double, ByVal Bruto As Double, ByVal QtdPecas As Integer) As System.Data.DataSet Implements wwwisc.ConsultaSoap.SalvaPesoBalanca
            Return MyBase.Channel.SalvaPesoBalanca(Usuario, Senha, Equip, Etiqueta, Liquido, Bruto, QtdPecas)
        End Function
        
        Public Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.AtualizaStatus
            Return MyBase.Channel.AtualizaStatus(Usuario, Senha, Equip, Etiqueta, Status)
        End Function
        
        Public Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As Integer, ByVal Coluna As Integer) As System.Data.DataSet Implements wwwisc.ConsultaSoap.SalvaLocaliza
            Return MyBase.Channel.SalvaLocaliza(Usuario, Senha, Equip, Etiqueta, Armazem, Num, Praca, Linha, Coluna)
        End Function
        
        Public Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.CarregaCombosUsu
            Return MyBase.Channel.CarregaCombosUsu(Usuario)
        End Function
        
        Public Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.RastrEtiqApres
            Return MyBase.Channel.RastrEtiqApres(EtiqApres)
        End Function
        
        Public Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.RastrEtiqRefCli
            Return MyBase.Channel.RastrEtiqRefCli(RefCli)
        End Function
        
        Public Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.RastrEtiqCodBarras
            Return MyBase.Channel.RastrEtiqCodBarras(AplRefBarras)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaSoap_ArquivoBin(ByVal request As wwwisc.ArquivoBinRequest) As wwwisc.ArquivoBinResponse Implements wwwisc.ConsultaSoap.ArquivoBin
            Return MyBase.Channel.ArquivoBin(request)
        End Function
        
        Public Function ArquivoBin(ByVal ArquivoEmDown As String) As Byte()
            Dim inValue As wwwisc.ArquivoBinRequest = New wwwisc.ArquivoBinRequest
            inValue.ArquivoEmDown = ArquivoEmDown
            Dim retVal As wwwisc.ArquivoBinResponse = CType(Me,wwwisc.ConsultaSoap).ArquivoBin(inValue)
            Return retVal.ArquivoBinResult
        End Function
        
        Public Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.DSCarregaRem
            Return MyBase.Channel.DSCarregaRem(Usuario, Senha, Equip, Consulta)
        End Function
        
        Public Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet Implements wwwisc.ConsultaSoap.DSGravaRem
            Return MyBase.Channel.DSGravaRem(Usuario, Senha, Equip, Consulta)
        End Function
        
        Public Function ArquivoMomentoModif(ByVal Arquivo As String) As Date Implements wwwisc.ConsultaSoap.ArquivoMomentoModif
            Return MyBase.Channel.ArquivoMomentoModif(Arquivo)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.intermesa.com.br/interface/", ConfigurationName:="wwwisc.ConsultaHttpGet")>  _
    Public Interface ConsultaHttpGet
        
        'CODEGEN: Generating message contract since the operation ObtemOpcArmazem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ObtemOpcArmazemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ObtemOpcArmazemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtemOpcArmazem(ByVal request As wwwisc.ObtemOpcArmazemRequest) As wwwisc.ObtemOpcArmazemResponse
        
        'CODEGEN: Generating message contract since the operation SalvaObs is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaObsRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaObsResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaObs(ByVal request As wwwisc.SalvaObsRequest) As wwwisc.SalvaObsResponse
        
        'CODEGEN: Generating message contract since the operation SalvaAvaria is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaAvariaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaAvariaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaAvaria(ByVal request As wwwisc.SalvaAvariaRequest) As wwwisc.SalvaAvariaResponse
        
        'CODEGEN: Generating message contract since the operation TrocaUnidMedida is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/TrocaUnidMedidaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/TrocaUnidMedidaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function TrocaUnidMedida(ByVal request As wwwisc.TrocaUnidMedidaRequest) As wwwisc.TrocaUnidMedidaResponse
        
        'CODEGEN: Generating message contract since the operation SalvaPesoBalanca is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaPesoBalancaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaPesoBalancaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaPesoBalanca(ByVal request As wwwisc.SalvaPesoBalancaRequest) As wwwisc.SalvaPesoBalancaResponse
        
        'CODEGEN: Generating message contract since the operation AtualizaStatus is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/AtualizaStatusRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/AtualizaStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AtualizaStatus(ByVal request As wwwisc.AtualizaStatusRequest) As wwwisc.AtualizaStatusResponse
        
        'CODEGEN: Generating message contract since the operation SalvaLocaliza is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaLocalizaRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/SalvaLocalizaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SalvaLocaliza(ByVal request As wwwisc.SalvaLocalizaRequest) As wwwisc.SalvaLocalizaResponse
        
        'CODEGEN: Generating message contract since the operation CarregaCombosUsu is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/CarregaCombosUsuRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/CarregaCombosUsuResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function CarregaCombosUsu(ByVal request As wwwisc.CarregaCombosUsuRequest) As wwwisc.CarregaCombosUsuResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqApres is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqApresRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqApresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqApres(ByVal request As wwwisc.RastrEtiqApresRequest) As wwwisc.RastrEtiqApresResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqRefCli is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqRefCliRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqRefCliResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqRefCli(ByVal request As wwwisc.RastrEtiqRefCliRequest) As wwwisc.RastrEtiqRefCliResponse
        
        'CODEGEN: Generating message contract since the operation RastrEtiqCodBarras is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqCodBarrasRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/RastrEtiqCodBarrasResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RastrEtiqCodBarras(ByVal request As wwwisc.RastrEtiqCodBarrasRequest) As wwwisc.RastrEtiqCodBarrasResponse
        
        'CODEGEN: Generating message contract since the operation ArquivoBin is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoBinRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoBinResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoBin(ByVal request As wwwisc.ArquivoBinRequest1) As wwwisc.ArquivoBinResponse1
        
        'CODEGEN: Generating message contract since the operation DSCarregaRem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSCarregaRemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSCarregaRemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSCarregaRem(ByVal request As wwwisc.DSCarregaRemRequest) As wwwisc.DSCarregaRemResponse
        
        'CODEGEN: Generating message contract since the operation DSGravaRem is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSGravaRemRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/DSGravaRemResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DSGravaRem(ByVal request As wwwisc.DSGravaRemRequest) As wwwisc.DSGravaRemResponse
        
        'CODEGEN: Generating message contract since the operation ArquivoMomentoModif is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoMomentoModifRequest", ReplyAction:="http://www.intermesa.com.br/interface/ConsultaHttpGet/ArquivoMomentoModifResponse"& _ 
            ""),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ArquivoMomentoModif(ByVal request As wwwisc.ArquivoMomentoModifRequest) As wwwisc.ArquivoMomentoModifResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtemOpcArmazemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Armazem As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Armazem As String)
            MyBase.New
            Me.Armazem = Armazem
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtemOpcArmazemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaObsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Texto As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Texto = Texto
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaObsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaAvariaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Texto As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Texto = Texto
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaAvariaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TrocaUnidMedidaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Pedido As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Item As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Unid As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As String, ByVal Unid As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Pedido = Pedido
            Me.Item = Item
            Me.Unid = Unid
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TrocaUnidMedidaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaPesoBalancaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Liquido As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Bruto As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public QtdPecas As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As String, ByVal Bruto As String, ByVal QtdPecas As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Liquido = Liquido
            Me.Bruto = Bruto
            Me.QtdPecas = QtdPecas
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaPesoBalancaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Status As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Status = Status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaLocalizaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Etiqueta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public Armazem As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public Num As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public Praca As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public Linha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Coluna As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As String, ByVal Coluna As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Etiqueta = Etiqueta
            Me.Armazem = Armazem
            Me.Num = Num
            Me.Praca = Praca
            Me.Linha = Linha
            Me.Coluna = Coluna
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalvaLocalizaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CarregaCombosUsuRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String)
            MyBase.New
            Me.Usuario = Usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CarregaCombosUsuResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqApresRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public EtiqApres As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EtiqApres As String)
            MyBase.New
            Me.EtiqApres = EtiqApres
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqApresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqRefCliRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RefCli As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RefCli As String)
            MyBase.New
            Me.RefCli = RefCli
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqRefCliResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqCodBarrasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AplRefBarras As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AplRefBarras As String)
            MyBase.New
            Me.AplRefBarras = AplRefBarras
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RastrEtiqCodBarrasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoBinRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public ArquivoEmDown As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ArquivoEmDown As String)
            MyBase.New
            Me.ArquivoEmDown = ArquivoEmDown
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoBinResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public base64Binary() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal base64Binary() As Byte)
            MyBase.New
            Me.base64Binary = base64Binary
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSCarregaRemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Consulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Consulta = Consulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSCarregaRemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSGravaRemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public Senha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public Equip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Consulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Senha = Senha
            Me.Equip = Equip
            Me.Consulta = Consulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DSGravaRemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoMomentoModifRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public Arquivo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Arquivo As String)
            MyBase.New
            Me.Arquivo = Arquivo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ArquivoMomentoModifResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.intermesa.com.br/interface/", Order:=0)>  _
        Public dateTime As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dateTime As Date)
            MyBase.New
            Me.dateTime = dateTime
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ConsultaHttpGetChannel
        Inherits wwwisc.ConsultaHttpGet, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ConsultaHttpGetClient
        Inherits System.ServiceModel.ClientBase(Of wwwisc.ConsultaHttpGet)
        Implements wwwisc.ConsultaHttpGet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_ObtemOpcArmazem(ByVal request As wwwisc.ObtemOpcArmazemRequest) As wwwisc.ObtemOpcArmazemResponse Implements wwwisc.ConsultaHttpGet.ObtemOpcArmazem
            Return MyBase.Channel.ObtemOpcArmazem(request)
        End Function
        
        Public Function ObtemOpcArmazem(ByVal Armazem As String) As System.Data.DataSet
            Dim inValue As wwwisc.ObtemOpcArmazemRequest = New wwwisc.ObtemOpcArmazemRequest
            inValue.Armazem = Armazem
            Dim retVal As wwwisc.ObtemOpcArmazemResponse = CType(Me,wwwisc.ConsultaHttpGet).ObtemOpcArmazem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_SalvaObs(ByVal request As wwwisc.SalvaObsRequest) As wwwisc.SalvaObsResponse Implements wwwisc.ConsultaHttpGet.SalvaObs
            Return MyBase.Channel.SalvaObs(request)
        End Function
        
        Public Function SalvaObs(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
            Dim inValue As wwwisc.SalvaObsRequest = New wwwisc.SalvaObsRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Texto = Texto
            Dim retVal As wwwisc.SalvaObsResponse = CType(Me,wwwisc.ConsultaHttpGet).SalvaObs(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_SalvaAvaria(ByVal request As wwwisc.SalvaAvariaRequest) As wwwisc.SalvaAvariaResponse Implements wwwisc.ConsultaHttpGet.SalvaAvaria
            Return MyBase.Channel.SalvaAvaria(request)
        End Function
        
        Public Function SalvaAvaria(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Texto As String) As System.Data.DataSet
            Dim inValue As wwwisc.SalvaAvariaRequest = New wwwisc.SalvaAvariaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Texto = Texto
            Dim retVal As wwwisc.SalvaAvariaResponse = CType(Me,wwwisc.ConsultaHttpGet).SalvaAvaria(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_TrocaUnidMedida(ByVal request As wwwisc.TrocaUnidMedidaRequest) As wwwisc.TrocaUnidMedidaResponse Implements wwwisc.ConsultaHttpGet.TrocaUnidMedida
            Return MyBase.Channel.TrocaUnidMedida(request)
        End Function
        
        Public Function TrocaUnidMedida(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Pedido As String, ByVal Item As String, ByVal Unid As String) As System.Data.DataSet
            Dim inValue As wwwisc.TrocaUnidMedidaRequest = New wwwisc.TrocaUnidMedidaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Pedido = Pedido
            inValue.Item = Item
            inValue.Unid = Unid
            Dim retVal As wwwisc.TrocaUnidMedidaResponse = CType(Me,wwwisc.ConsultaHttpGet).TrocaUnidMedida(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_SalvaPesoBalanca(ByVal request As wwwisc.SalvaPesoBalancaRequest) As wwwisc.SalvaPesoBalancaResponse Implements wwwisc.ConsultaHttpGet.SalvaPesoBalanca
            Return MyBase.Channel.SalvaPesoBalanca(request)
        End Function
        
        Public Function SalvaPesoBalanca(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Liquido As String, ByVal Bruto As String, ByVal QtdPecas As String) As System.Data.DataSet
            Dim inValue As wwwisc.SalvaPesoBalancaRequest = New wwwisc.SalvaPesoBalancaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Liquido = Liquido
            inValue.Bruto = Bruto
            inValue.QtdPecas = QtdPecas
            Dim retVal As wwwisc.SalvaPesoBalancaResponse = CType(Me,wwwisc.ConsultaHttpGet).SalvaPesoBalanca(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_AtualizaStatus(ByVal request As wwwisc.AtualizaStatusRequest) As wwwisc.AtualizaStatusResponse Implements wwwisc.ConsultaHttpGet.AtualizaStatus
            Return MyBase.Channel.AtualizaStatus(request)
        End Function
        
        Public Function AtualizaStatus(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Status As String) As System.Data.DataSet
            Dim inValue As wwwisc.AtualizaStatusRequest = New wwwisc.AtualizaStatusRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Status = Status
            Dim retVal As wwwisc.AtualizaStatusResponse = CType(Me,wwwisc.ConsultaHttpGet).AtualizaStatus(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_SalvaLocaliza(ByVal request As wwwisc.SalvaLocalizaRequest) As wwwisc.SalvaLocalizaResponse Implements wwwisc.ConsultaHttpGet.SalvaLocaliza
            Return MyBase.Channel.SalvaLocaliza(request)
        End Function
        
        Public Function SalvaLocaliza(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Etiqueta As String, ByVal Armazem As String, ByVal Num As String, ByVal Praca As String, ByVal Linha As String, ByVal Coluna As String) As System.Data.DataSet
            Dim inValue As wwwisc.SalvaLocalizaRequest = New wwwisc.SalvaLocalizaRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Etiqueta = Etiqueta
            inValue.Armazem = Armazem
            inValue.Num = Num
            inValue.Praca = Praca
            inValue.Linha = Linha
            inValue.Coluna = Coluna
            Dim retVal As wwwisc.SalvaLocalizaResponse = CType(Me,wwwisc.ConsultaHttpGet).SalvaLocaliza(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_CarregaCombosUsu(ByVal request As wwwisc.CarregaCombosUsuRequest) As wwwisc.CarregaCombosUsuResponse Implements wwwisc.ConsultaHttpGet.CarregaCombosUsu
            Return MyBase.Channel.CarregaCombosUsu(request)
        End Function
        
        Public Function CarregaCombosUsu(ByVal Usuario As String) As System.Data.DataSet
            Dim inValue As wwwisc.CarregaCombosUsuRequest = New wwwisc.CarregaCombosUsuRequest
            inValue.Usuario = Usuario
            Dim retVal As wwwisc.CarregaCombosUsuResponse = CType(Me,wwwisc.ConsultaHttpGet).CarregaCombosUsu(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_RastrEtiqApres(ByVal request As wwwisc.RastrEtiqApresRequest) As wwwisc.RastrEtiqApresResponse Implements wwwisc.ConsultaHttpGet.RastrEtiqApres
            Return MyBase.Channel.RastrEtiqApres(request)
        End Function
        
        Public Function RastrEtiqApres(ByVal EtiqApres As String) As System.Data.DataSet
            Dim inValue As wwwisc.RastrEtiqApresRequest = New wwwisc.RastrEtiqApresRequest
            inValue.EtiqApres = EtiqApres
            Dim retVal As wwwisc.RastrEtiqApresResponse = CType(Me,wwwisc.ConsultaHttpGet).RastrEtiqApres(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_RastrEtiqRefCli(ByVal request As wwwisc.RastrEtiqRefCliRequest) As wwwisc.RastrEtiqRefCliResponse Implements wwwisc.ConsultaHttpGet.RastrEtiqRefCli
            Return MyBase.Channel.RastrEtiqRefCli(request)
        End Function
        
        Public Function RastrEtiqRefCli(ByVal RefCli As String) As System.Data.DataSet
            Dim inValue As wwwisc.RastrEtiqRefCliRequest = New wwwisc.RastrEtiqRefCliRequest
            inValue.RefCli = RefCli
            Dim retVal As wwwisc.RastrEtiqRefCliResponse = CType(Me,wwwisc.ConsultaHttpGet).RastrEtiqRefCli(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_RastrEtiqCodBarras(ByVal request As wwwisc.RastrEtiqCodBarrasRequest) As wwwisc.RastrEtiqCodBarrasResponse Implements wwwisc.ConsultaHttpGet.RastrEtiqCodBarras
            Return MyBase.Channel.RastrEtiqCodBarras(request)
        End Function
        
        Public Function RastrEtiqCodBarras(ByVal AplRefBarras As String) As System.Data.DataSet
            Dim inValue As wwwisc.RastrEtiqCodBarrasRequest = New wwwisc.RastrEtiqCodBarrasRequest
            inValue.AplRefBarras = AplRefBarras
            Dim retVal As wwwisc.RastrEtiqCodBarrasResponse = CType(Me,wwwisc.ConsultaHttpGet).RastrEtiqCodBarras(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_ArquivoBin(ByVal request As wwwisc.ArquivoBinRequest1) As wwwisc.ArquivoBinResponse1 Implements wwwisc.ConsultaHttpGet.ArquivoBin
            Return MyBase.Channel.ArquivoBin(request)
        End Function
        
        Public Function ArquivoBin(ByVal ArquivoEmDown As String) As Byte()
            Dim inValue As wwwisc.ArquivoBinRequest1 = New wwwisc.ArquivoBinRequest1
            inValue.ArquivoEmDown = ArquivoEmDown
            Dim retVal As wwwisc.ArquivoBinResponse1 = CType(Me,wwwisc.ConsultaHttpGet).ArquivoBin(inValue)
            Return retVal.base64Binary
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_DSCarregaRem(ByVal request As wwwisc.DSCarregaRemRequest) As wwwisc.DSCarregaRemResponse Implements wwwisc.ConsultaHttpGet.DSCarregaRem
            Return MyBase.Channel.DSCarregaRem(request)
        End Function
        
        Public Function DSCarregaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
            Dim inValue As wwwisc.DSCarregaRemRequest = New wwwisc.DSCarregaRemRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Consulta = Consulta
            Dim retVal As wwwisc.DSCarregaRemResponse = CType(Me,wwwisc.ConsultaHttpGet).DSCarregaRem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_DSGravaRem(ByVal request As wwwisc.DSGravaRemRequest) As wwwisc.DSGravaRemResponse Implements wwwisc.ConsultaHttpGet.DSGravaRem
            Return MyBase.Channel.DSGravaRem(request)
        End Function
        
        Public Function DSGravaRem(ByVal Usuario As String, ByVal Senha As String, ByVal Equip As String, ByVal Consulta As String) As System.Data.DataSet
            Dim inValue As wwwisc.DSGravaRemRequest = New wwwisc.DSGravaRemRequest
            inValue.Usuario = Usuario
            inValue.Senha = Senha
            inValue.Equip = Equip
            inValue.Consulta = Consulta
            Dim retVal As wwwisc.DSGravaRemResponse = CType(Me,wwwisc.ConsultaHttpGet).DSGravaRem(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wwwisc_ConsultaHttpGet_ArquivoMomentoModif(ByVal request As wwwisc.ArquivoMomentoModifRequest) As wwwisc.ArquivoMomentoModifResponse Implements wwwisc.ConsultaHttpGet.ArquivoMomentoModif
            Return MyBase.Channel.ArquivoMomentoModif(request)
        End Function
        
        Public Function ArquivoMomentoModif(ByVal Arquivo As String) As Date
            Dim inValue As wwwisc.ArquivoMomentoModifRequest = New wwwisc.ArquivoMomentoModifRequest
            inValue.Arquivo = Arquivo
            Dim retVal As wwwisc.ArquivoMomentoModifResponse = CType(Me,wwwisc.ConsultaHttpGet).ArquivoMomentoModif(inValue)
            Return retVal.dateTime
        End Function
    End Class
End Namespace
